#version 450
// generated by tools/srvk_shader_transform.py from rawsr/bayer_quad_gray.glsl (sources stay ESSL)
layout(binding = 2, std140) uniform SrUniforms {
    highp uvec3 u_dispatch_offset; // src:2
    ivec2 u_size; // src:9
};
// SPDX-License-Identifier: GPL-3.0-or-later
precision highp float;
precision highp sampler2D;
precision highp image2D;
layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform sampler2D u_cfa;
layout(binding = 1, r32f) writeonly uniform highp image2D img_gray;
void main() {
    ivec2 p = ivec2((gl_GlobalInvocationID + u_dispatch_offset).xy);
    if (any(greaterThanEqual(p, u_size))) return;
    ivec2 q = p * 2;
    float gray = texelFetch(u_cfa, q, 0).r + texelFetch(u_cfa, q + ivec2(1, 0), 0).r
        + texelFetch(u_cfa, q + ivec2(0, 1), 0).r + texelFetch(u_cfa, q + ivec2(1), 0).r;
    imageStore(img_gray, p, vec4(gray * 0.25));
}
