#version 450
// generated by tools/srvk_shader_transform.py from quad/color.glsl (sources stay ESSL)
// SPDX-License-Identifier: GPL-3.0-or-later
// Adapted from PhotonCamera demosaicp2quad: green-guided color ratios with
// a linear fallback near black/clipping. Generalized to every Bayer order,
// sensor crop phase and defined color-preserving border reads.
// SPDX-License-Identifier: GPL-3.0-or-later
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp image2D;
layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform sampler2D u_raw;
layout(binding = 3, std140) uniform SrUniforms {
    ivec2 u_size; // src:13
    ivec2 u_origin; // src:14
    ivec4 u_fc; // src:15
    vec3 u_balance; // src:16
    mat3 u_camera_to_acescg; // src:39
    vec3 u_camera_white_normalized; // src:40
};

// Extend by the 4x4 CFA period. Plain clamping could substitute another color.
ivec2 bounded(ivec2 p) {
    ivec2 phase = ((p % 4) + 4) % 4;
    return clamp(p, phase, u_size - 1 - ((u_size - 1 - phase) % 4));
}
int colorAt(ivec2 p) {
    ivec2 group = (bounded(p) + u_origin) / 2;
    return u_fc[((group.y & 1) << 1) | (group.x & 1)];
}
float raw(ivec2 p) {
    return texelFetch(u_raw, bounded(p), 0).r * u_balance[colorAt(p)];
}
ivec2 shiftAt(ivec2 p) { return (p + u_origin) & 1; }
// Within-group differences, corresponding to PhotonCamera demosaicp0quad.
vec2 gradient(ivec2 p) {
    ivec2 shift = shiftAt(p);
    return 0.5 * (vec2(raw(p + ivec2(1 - 2 * shift.x, 0)),
                       raw(p + ivec2(0, 1 - 2 * shift.y))) - raw(p));
}

layout(binding = 1) uniform sampler2D u_green;
layout(binding = 2, rgba16f) writeonly uniform highp image2D img_out;
float green(ivec2 p) { return texelFetch(u_green, bounded(p), 0).r; }
bool ratioSafe(float g) { return g >= 0.01 && g <= 0.99; }
float interpolate(ivec2 p, int target) {
    if (colorAt(p) == target) return raw(p);
    ivec2 shift = shiftAt(p);
    ivec2 lo = -1 - shift;
    ivec2 hi = 2 - shift;
    ivec2 taps[4];
    int count;
    if (colorAt(p + ivec2(lo.x, 0)) == target) {
        count = 2;
        taps[0] = p + ivec2(lo.x, 0); taps[1] = p + ivec2(hi.x, 0);
    } else if (colorAt(p + ivec2(0, lo.y)) == target) {
        count = 2;
        taps[0] = p + ivec2(0, lo.y); taps[1] = p + ivec2(0, hi.y);
    } else {
        count = 4;
        taps[0] = p + lo; taps[1] = p + ivec2(hi.x, lo.y);
        taps[2] = p + ivec2(lo.x, hi.y); taps[3] = p + hi;
    }
    float g = green(p);
    bool useRatio = ratioSafe(g);
    float average = 0.0, ratio = 0.0;
    for (int i = 0; i < count; ++i) {
        float tapGreen = green(taps[i]);
        float tapRaw = raw(taps[i]);
        useRatio = useRatio && ratioSafe(tapGreen);
        average += tapRaw;
        ratio += tapRaw / max(tapGreen, 0.000001);
    }
    return (useRatio ? g * ratio : average) / float(count);
}
void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(p, u_size))) return;
    vec3 cameraRgb = max(vec3(interpolate(p, 0), green(p), interpolate(p, 2)), vec3(0));
    vec3 blend = smoothstep(vec3(0.70), vec3(0.99), cameraRgb);
    cameraRgb = mix(cameraRgb, u_camera_white_normalized, max(blend.r, max(blend.g, blend.b)));
    imageStore(img_out, p, vec4(u_camera_to_acescg * cameraRgb, 1.0));
}
