#version 450
// generated by tools/srvk_shader_transform.py from rawsr/lk_refine.glsl (sources stay ESSL)
layout(binding = 4, std140) uniform SrUniforms {
    highp uvec3 u_dispatch_offset; // src:2
    ivec2 u_ref_size,u_mov_size,u_tile_grid; // src:20
    int u_tile_size,u_search_radius,u_iterations; // src:21
};
// SPDX-License-Identifier: GPL-3.0-or-later
// JAMY-L inverse-compositional refinement 1:1 (ICA.py cpu_ica via
// RawSrCoreAlign.steepestSums/treeClippedSums/icaStep/meanAbsidual):
// unhalved zero-padded central-difference gradients, full-tile Hessian,
// |det| < 1e-10 keeps the seed flow (residual still computed). Per-size
// quirks transcribed verbatim: 8 clamps its sampler (frac from the
// unclamped floor) and tree-clips reduction partials to +-radius with an
// unclipped step; 16/32/64 zero-fill and clip the step to +-radius (64
// with the clip disabled at 32767, reference ica.clip=False for ts 64).
// (Retired: the old CUDA 64-kernel sliding window with its off-by-one
// bottom row; the current reference cpu_ica has no 64 path.) Output w
// is the det verdict (diagnostic; downstream consumes xy only).
precision highp float;
precision highp int;
precision highp sampler2D;
layout(local_size_x=1,local_size_y=1) in;
layout(binding = 0) uniform sampler2D u_reference;
layout(binding = 1) uniform sampler2D u_moving;
layout(binding = 2) uniform sampler2D u_flow;
layout(binding = 3, rgba32f) writeonly uniform highp image2D img_refined;
float refTap(ivec2 p){return texelFetch(u_reference,p,0).r;}
float movTapZero(ivec2 p){
 if(any(lessThan(p,ivec2(0)))||any(greaterThanEqual(p,u_mov_size)))return 0.0;
 return texelFetch(u_moving,p,0).r;
}
float sampleZero(vec2 q){
 ivec2 f=ivec2(floor(q));vec2 frac=q-vec2(f);
 float m00=movTapZero(f),m01=movTapZero(f+ivec2(1,0));
 float m10=movTapZero(f+ivec2(0,1)),m11=movTapZero(f+ivec2(1,1));
 float top=m00+(m01-m00)*frac.x;
 float bot=m10+(m11-m10)*frac.x;
 return top+(bot-top)*frac.y;
}
float sampleClamped(vec2 q){
 ivec2 f=ivec2(floor(q));vec2 frac=q-vec2(f);
 ivec2 f0=clamp(f,ivec2(0),u_mov_size-ivec2(1));
 ivec2 f1=min(f0+ivec2(1),u_mov_size-ivec2(1));
 float m00=texelFetch(u_moving,f0,0).r;
 float m01=texelFetch(u_moving,ivec2(f1.x,f0.y),0).r;
 float m10=texelFetch(u_moving,ivec2(f0.x,f1.y),0).r;
 float m11=texelFetch(u_moving,f1,0).r;
 float top=m00+(m01-m00)*frac.x;
 float bot=m10+(m11-m10)*frac.x;
 return top+(bot-top)*frac.y;
}
vec2 refGrad(ivec2 p){
 float left=p.x>0?refTap(p-ivec2(1,0)):0.0;
 float right=p.x<u_ref_size.x-1?refTap(p+ivec2(1,0)):0.0;
 float up=p.y>0?refTap(p-ivec2(0,1)):0.0;
 float down=p.y<u_ref_size.y-1?refTap(p+ivec2(0,1)):0.0;
 return vec2(right-left,down-up);
}
void main(){
 ivec2 tile=ivec2((gl_GlobalInvocationID + u_dispatch_offset).xy);if(any(greaterThanEqual(tile,u_tile_grid)))return;
 ivec2 origin=tile*u_tile_size;
 vec2 flow=texelFetch(u_flow,tile,0).xy;
 float h00=0.0,h01=0.0,h11=0.0;
 for(int y=0;y<64;y++){
  if(y>=u_tile_size)break;
  for(int x=0;x<64;x++){
   if(x>=u_tile_size)break;
   vec2 g=refGrad(origin+ivec2(x,y));
   h00+=g.x*g.x;h01+=g.x*g.y;h11+=g.y*g.y;
  }
 }
 float det=h00*h11-h01*h01;
 bool solvable=abs(det)>=1e-10;
 float clip=u_tile_size==64?32767.0:float(u_search_radius);
 if(solvable){
  float detInv=1.0/det;
  for(int iter=0;iter<5;iter++){
   if(iter>=u_iterations)break;
   if(u_tile_size==8){
    float c0[64];float c1[64];
    for(int y=0;y<8;y++){
     for(int x=0;x<8;x++){
      ivec2 p=origin+ivec2(x,y);
      float e=sampleClamped(vec2(p)+flow)-refTap(p);
      vec2 g=refGrad(p);
      c0[y*8+x]=-g.x*e;c1[y*8+x]=-g.y*e;
     }
    }
    int n=32;
    while(n>0){
     for(int tid=0;tid<32;tid++){
      if(tid>=n)break;
      c0[tid]+=clamp(c0[tid+n],-clip,clip);
      c1[tid]+=clamp(c1[tid+n],-clip,clip);
     }
     n/=2;
    }
    flow+=detInv*vec2(h11*c0[0]-h01*c1[0],-h01*c0[0]+h00*c1[0]);
   }else{
    float b0=0.0,b1=0.0;
    for(int y=0;y<64;y++){
     if(y>=u_tile_size)break;
     for(int x=0;x<64;x++){
      if(x>=u_tile_size)break;
      ivec2 p=origin+ivec2(x,y);
      float e=sampleZero(vec2(p)+flow)-refTap(p);
      vec2 g=refGrad(p);
      b0+=-g.x*e;b1+=-g.y*e;
     }
    }
    flow+=clamp(detInv*vec2(h11*b0-h01*b1,-h01*b0+h00*b1),vec2(-clip),vec2(clip));
   }
  }
 }
 float residual=0.0;
 for(int y=0;y<64;y++){
  if(y>=u_tile_size)break;
  for(int x=0;x<64;x++){
   if(x>=u_tile_size)break;
   ivec2 p=origin+ivec2(x,y);
   float s=u_tile_size==8?sampleClamped(vec2(p)+flow):sampleZero(vec2(p)+flow);
   residual+=abs(s-refTap(p));
  }
 }
 residual/=float(u_tile_size*u_tile_size);
 imageStore(img_refined,tile,vec4(flow,residual,solvable?1.0:0.0));
}
