#version 450
// generated by tools/srvk_shader_transform.py from rawsr/lk_refine.glsl (sources stay ESSL)
layout(binding = 4, std140) uniform SrUniforms {
    highp uvec3 u_dispatch_offset; // src:2
    ivec2 u_size,u_tile_grid; // src:9
    int u_tile_size; // src:10
    float u_min_determinant,u_max_residual,u_min_condition,u_min_fraction; // src:11
};
// SPDX-License-Identifier: GPL-3.0-or-later
precision highp float;
precision highp int;
precision highp sampler2D;
layout(local_size_x=1,local_size_y=1) in;
layout(binding = 0) uniform sampler2D u_reference;
layout(binding = 1) uniform sampler2D u_moving;
layout(binding = 2) uniform sampler2D u_flow;
layout(binding = 3, rgba32f) writeonly uniform highp image2D img_refined;
bool finite(float x){return !isnan(x)&&!isinf(x);}
bool inside(vec2 q){return all(greaterThanEqual(q,vec2(0)))&&all(lessThan(q,vec2(u_size-1)));}
bool templateInside(ivec2 p){return all(greaterThan(p,ivec2(0)))&&all(lessThan(p,u_size-1));}
vec2 gradient(ivec2 p){return 0.5*vec2(
 texelFetch(u_reference,p+ivec2(1,0),0).r-texelFetch(u_reference,p-ivec2(1,0),0).r,
 texelFetch(u_reference,p+ivec2(0,1),0).r-texelFetch(u_reference,p-ivec2(0,1),0).r);}
float sampleMoving(vec2 p){
 ivec2 q=ivec2(floor(p));vec2 f=p-vec2(q);
 float a=texelFetch(u_moving,q,0).r*(1.0-f.x)+texelFetch(u_moving,q+ivec2(1,0),0).r*f.x;
 float b=texelFetch(u_moving,q+ivec2(0,1),0).r*(1.0-f.x)+texelFetch(u_moving,q+ivec2(1,1),0).r*f.x;
 return a*(1.0-f.y)+b*f.y;
}
void main(){
 ivec2 tile=ivec2((gl_GlobalInvocationID + u_dispatch_offset).xy);if(any(greaterThanEqual(tile,u_tile_grid)))return;
 ivec2 origin=tile*u_tile_size,end=min(origin+ivec2(u_tile_size),u_size);
 vec4 initial=texelFetch(u_flow,tile,0);vec2 flow=initial.xy;
 float hxx=0.0,hxy=0.0,hyy=0.0;int samples=0;
 for(int y=0;y<32;y++){if(origin.y+y>=end.y)break;
  for(int x=0;x<32;x++){if(origin.x+x>=end.x)break;
   ivec2 p=origin+ivec2(x,y);if(!templateInside(p))continue;
   vec2 g=gradient(p);hxx+=g.x*g.x;hxy+=g.x*g.y;hyy+=g.y*g.y;samples++;
  }
 }
 float determinant=hxx*hyy-hxy*hxy,trace=hxx+hyy;
 bool valid=initial.w>0.0&&samples>=4&&finite(determinant)&&determinant>u_min_determinant&&determinant>u_min_condition*trace*trace;
 // Exactly three finest-level IC updates; failed tiles stay rejected.
 for(int iteration=0;iteration<3;iteration++){
  float bx=0.0,by=0.0;int count=0;
  if(valid){
   for(int y=0;y<32;y++){if(origin.y+y>=end.y)break;
    for(int x=0;x<32;x++){if(origin.x+x>=end.x)break;
     ivec2 p=origin+ivec2(x,y);vec2 q=vec2(p)+flow;
     if(!templateInside(p)||!inside(q))continue;
     vec2 g=gradient(p);float e=sampleMoving(q)-texelFetch(u_reference,p,0).r;
     bx+=g.x*e;by+=g.y*e;count++;
    }
   }
   valid=count==samples&&finite(bx)&&finite(by);
   if(valid){
    vec2 step=vec2(hyy*bx-hxy*by,hxx*by-hxy*bx)/determinant;
    valid=finite(step.x)&&finite(step.y);
    if(valid)flow-=clamp(step,vec2(-1),vec2(1));
   }
  }
 }
 float residual=0.0;int count=0;
 for(int y=0;y<32;y++){if(origin.y+y>=end.y)break;
  for(int x=0;x<32;x++){if(origin.x+x>=end.x)break;
   ivec2 p=origin+ivec2(x,y);vec2 q=vec2(p)+flow;
   if(!inside(q))continue;
   residual+=abs(sampleMoving(q)-texelFetch(u_reference,p,0).r);count++;
  }
 }
 int area=(end.x-origin.x)*(end.y-origin.y);
 bool enough=count>=max(4,int(ceil(float(area)*u_min_fraction)));
 residual=enough&&finite(residual)?min(residual/float(count),1e6):1e6;
 valid=valid&&enough&&residual<=u_max_residual;
 imageStore(img_refined,tile,vec4(flow,residual,valid?1.0:0.0));
}
