#version 450
// generated by tools/srvk_shader_transform.py from rawsr/merge_finalize.glsl (sources stay ESSL)
layout(binding = 6, std140) uniform SrUniforms {
    highp uvec3 u_dispatch_offset; // src:2
    ivec2 u_size; // src:20
};
// SPDX-License-Identifier: GPL-3.0-or-later
// Jamy-L merge finalization (`utils.divide`): per output pixel, adds the
// reference-last contribution into the moving-frame accumulators and
// normalizes each channel independently with eps = 1e-8. Zero support
// divides to 0 (the reference NaN blacked downstream). The fallback mask
// records every pixel where at least one channel had no support or the
// quotient was non-finite. Non-finite outputs reset to zero, mirroring the
// RawSrBayerMerge oracle.
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp image2D;
layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform sampler2D u_num;
layout(binding = 1) uniform sampler2D u_den;
layout(binding = 2) uniform sampler2D u_ref_num;
layout(binding = 3) uniform sampler2D u_ref_den;
layout(binding = 4, rgba32f) writeonly uniform highp image2D img_out;
layout(binding = 5, r32f) writeonly uniform highp image2D img_fallback;
const float EPS = 1e-8;
bool finite(float x) { return !isnan(x) && !isinf(x); }
float pick(float totalNum, float totalDen) {
    if (!(totalDen > EPS)) return 0.0;
    float v = totalNum / max(totalDen, EPS);
    return finite(v) ? v : 0.0;
}
void main() {
    ivec2 p = ivec2((gl_GlobalInvocationID + u_dispatch_offset).xy);
    if (any(greaterThanEqual(p, u_size))) return;
    vec4 num = texelFetch(u_num, p, 0) + texelFetch(u_ref_num, p, 0);
    vec4 den = texelFetch(u_den, p, 0) + texelFetch(u_ref_den, p, 0);
    float r = pick(num.x, den.x);
    float g = pick(num.y, den.y);
    float b = pick(num.z, den.z);
    float fellBack = (den.x <= EPS || den.y <= EPS || den.z <= EPS
        || !finite(num.x / max(den.x, EPS)) || !finite(num.y / max(den.y, EPS))
        || !finite(num.z / max(den.z, EPS))) ? 1.0 : 0.0;
    imageStore(img_out, p, vec4(r, g, b, 1.0));
    imageStore(img_fallback, p, vec4(fellBack));
}
