#version 450
// generated by tools/srvk_shader_transform.py from rawsr/unblocker_downsample.glsl (sources stay ESSL)
layout(binding = 2, std140) uniform SrUniforms {
    highp uvec3 u_dispatch_offset; // src:2
    ivec2 u_size; // src:15
    ivec2 u_full_size; // src:16
};
// SPDX-License-Identifier: GPL-3.0-or-later
// Unblocker half-quad box mean (Sabre UnblockerBlur analogue). One invocation
// per half-quad: the mean of its 2x2 quad taps from the full quad gray plane.
// Edge half-cells average the available taps; the count can never reach zero
// (every half-cell covers at least one quad). Mirrors the half-grid build in
// RawSrUnblocker.computeFrame exactly, including non-finite tap exclusion.
precision highp float;
precision highp int;
precision highp sampler2D;
precision highp image2D;
layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform sampler2D u_gray;
layout(binding = 1, r32f) writeonly uniform highp image2D img_half;
bool finite(float x) { return !isnan(x) && !isinf(x); }
void main() {
    ivec2 h = ivec2((gl_GlobalInvocationID + u_dispatch_offset).xy);
    if (any(greaterThanEqual(h, u_size))) return;
    float sum = 0.0;
    int count = 0;
    for (int i = 0; i <= 1; i++) {
        for (int j = 0; j <= 1; j++) {
            ivec2 q = h * 2 + ivec2(j, i);
            if (any(greaterThanEqual(q, u_full_size))) continue;
            float v = texelFetch(u_gray, q, 0).r;
            if (!finite(v)) continue;
            sum += v;
            count++;
        }
    }
    float outValue = count > 0 ? sum / float(count) : 0.0;
    imageStore(img_half, h, vec4(outValue));
}
